### ISSUE TITLE
Setup does not work in Windows

### ISSUE THREAD

**Issue by pleverett** [RicardoValdovinos/vite-react-boilerplate#16]
The current "setup" script uses "rm" to clean up, but "rm" is not available in the Windows environment. This can be fix by adding the https://github.com/shelljs/shx package as a DEV dependency and adding "shx" in front of "rm" in the script:

"setup": "git init && npx husky init && npx playwright install && shx rm .husky/pre-commit"

I made the change and tested locally on my Windows machine and can submit a pull request.

**Comment by RicardoValdovinos** [comment]
Yes, that'd be great!

**Comment by RicardoValdovinos** [comment]
shx added and packages update.
