### ISSUE TITLE
rootRoute._addFileChildren is not a function

### ISSUE THREAD

**Issue by simida0852** [RicardoValdovinos/vite-react-boilerplate#17]
Hi author, thank you very much for the framework!
However, I have the problem in the picture after running the project according to the guide.

![image](https://github.com/user-attachments/assets/50804d6c-7548-4cfe-ae4c-64377fb60216)

**Comment by RicardoValdovinos** [comment]
Hello,

I am not able to reproduce this error after following the steps in the README. Can you provide additional information/context?

If you delete routeTree.gen.ts and allow it to regenerate do you receive the same error?

**Comment by simida0852** [comment]
Thank you.
Yes, I completely follow the `readme` to operate. Colleague, I deleted and regenerated this file `routeTree.gen.ts`, but the problem still exists
mac os 12.6
nodejs v18.19.0
pnpm 8.6.10
![image](https://github.com/user-attachments/assets/8805363c-ad14-4279-a959-ddd05424c177)

**Comment by younesDev00** [comment]
this exists when creating a route while still developing I was able to reproduce this error by generating a route called `about` then deleting it, then navigating to the route, I was also able to get this error when navigating to a route that was created after the deleted route. 

edit: this seems to only be showing with the `vitejs/plugin-react-swc` compiler

**Comment by RicardoValdovinos** [comment]
I'm still not able to replicate this issue. If it is a problem with `@vitejs/plugin-react-swc` feel free to remove the package and replace it with `@vitejs/plugin-react`. After you've made the replacement you will have to update `vite.config.ts`. Replace `import react from "@vitejs/plugin-react-swc";` with `import react from "@vitejs/plugin-react";`

As a reference, this is what I see on my end when I delete and add/readd routes and navigate to them/refresh the page 
![image](https://github.com/user-attachments/assets/3c20d834-7ccc-4b0d-9478-c64fbcd6efb4)

**Comment by simida0852** [comment]
Thanks for the reply, it might be a problem with my environment configuration
