### ISSUE TITLE
Generating Routes

### ISSUE THREAD

**Issue by younesDev00** [RicardoValdovinos/vite-react-boilerplate#19]
will need to add `@tanstack/router-cli` to generate routes

**Comment by RicardoValdovinos** [comment]
As per the [tanstack router documentation](https://tanstack.com/router/v1/docs/framework/react/guide/file-based-routing#installation), you can use TanStack Router CLI or plugins if you are using a bundler (vite).

In our case, route autogeneration should already be handled by `@tanstack/router-plugin` and `@vitejs/plugin-react-swc`. If you want/need to use babel, you should use `@vitejs/plugin-react`.  [Configuration with Vite](https://tanstack.com/router/v1/docs/framework/react/guide/file-based-routing#configuration-with-vite)
