### ISSUE TITLE
unecessary some Dockerfile command

### ISSUE THREAD

**Issue by oxwazz** [RicardoValdovinos/vite-react-boilerplate#6]
in the build tutorial we just call the `pnpm build` which is this generate dist folder, but in the Dockerfile you just call the same command again, i think this is redundant (unecessary)

**Comment by oxwazz** [comment]
@RicardoValdovinos  i have the [pull request](https://github.com/RicardoValdovinos/vite-react-boilerplate/pull/7) if you want to delete the command

**Comment by RicardoValdovinos** [comment]
Thank you for the PR! I've gone ahead and merged it.
